name: HeiChips Project Submission
description: Use this template to submit your HeiChips group project for tapeout.
title: "[HeiChips Submission]: <project_name>"
assignees:
- mole99
labels:
- submission-pending
body:
  - type: markdown
    attributes:
      value: |
        # HeiChips Project Submission
        
        Please fill out the information below in order to submit your group project for tapeout.
        
        ---

  - type: textarea
    id: repository
    attributes:
      label: Repository
      description: The link to your group project repository.
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Preferred project location?
      description: Do you have a preferred project location? For example, on the left or right side of the chip, or a fixed project coordinate e.g. X0Y1. If not, just leave empty.

  - type: textarea
    id: pcb-requirements
    attributes:
      label: PCB Requirements
      description: Does your design have any special requirements for the HeiChips PCB? For example, a USB connector on specific pins, or a QSPI flash, etc. If not, leave empty. We will definitely add some LEDs and Pmod connectors to the board, so these do not have to be listed here.

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Anything else you want to let us know.

  - type: markdown
    attributes:
      value: |
        ## User Project Bitstream

        While this is not mandatory to provide by the time of the submission deadline, please also consider adding an example bitstream for your project at some point in time. This allows you, us and everyone else to test your design once we get the chips back. You can find instructions on how to generate a bitstream [here](https://github.com/HeiChips/heichips26-tapeout/tree/main/ip/fabric/user_designs).
